# Generated by Django 2.2 on 2019-05-17 13:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C1', '1'), ('C2', '2'), ('C3', '3'), ('C4', '4')], max_length=100)),
                ('productName', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4'), ('E', '5'), ('F', '6'), ('G', '7'), ('H', '8'), ('I', '9')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productWeightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerdata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
