# Generated by Django 2.2 on 2019-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twfApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerdata',
            name='name',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='centerdata',
            name='productName',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=100),
        ),
    ]
